[project]
name = "pexpect-cli"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pexpect>=4.9.0",
]

[project.scripts]
pexpect-server = "pexpect_cli.server:main"
pexpect-cli = "pexpect_cli.client:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
