[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#fdf6e3"
foreground = "#586e75"

[cursor]
style = "Block"

[font]
size = 15.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\r"
key = "NumpadEnter"

[scrolling]
history = 0

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"
